In [3]:
scores = [78, 69, 65]
new_scores = []

for score in scores:
    new_scores.append(score + 3)

new_scores

[81, 72, 68]

In [4]:
#list comprehention(快速建立list)
scores = [78, 69, 65]
new_scores = [score+3 for score in scores]
new_scores

[81, 72, 68]

In [6]:
scores = [78, 69, 65]
scores * 2

[78, 69, 65, 78, 69, 65]

In [7]:
[67, 92, 85] + [78, 69, 65]

[67, 92, 85, 78, 69, 65]

In [5]:
import numpy as np

scores = np.array([78, 69, 65])
print(type(scores))
scores + 3

<class 'numpy.ndarray'>


array([81, 72, 68])

In [12]:
scores.sum()
scores.mean()
scores.std()
scores.min()
scores.max()
np.median(scores)


np.float64(69.0)

In [14]:
students = np.array([
    [67, 94, 65],
    [78, 92, 68],
    [59, 92, 87]
    ])
students

array([[67, 94, 65],
       [78, 92, 68],
       [59, 92, 87]])

In [ ]:
#常用的查詢屬性
students.ndim, students.size, students.shape, students.dtype

(2, 9, (3, 3), dtype('int64'))

In [19]:
students[0,0]

np.int64(67)

In [ ]:
#第1位學生分數
students[0,:]

array([67, 94, 65])

In [21]:
#前2個學生
students[0:2,:]

array([[67, 94, 65],
       [78, 92, 68]])

In [26]:
#最後2個學生
students[-2:] + 3

array([[81, 95, 71],
       [62, 95, 90]])

In [24]:
#國文
students[:,0]

array([67, 78, 59])

In [25]:
students[:,:2]

array([[67, 94],
       [78, 92],
       [59, 92]])